env:
  node: true
  es2021: true
  jest: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
globals:
  process: 'readonly'
rules:
  indent: ['error', 2]
  quotes: ['error', 'single']
  semi: ['error', 'always']
  no-console: 'off'